### ISSUE TITLE
error import module easysnmp

### ISSUE THREAD

**Issue by xuys50** [gmambro/easysnmp#1]
Platform: Openwrt on ARM

root@91WK-RT50:~# pip install easysnmp
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: easysnmp in /usr/lib/python2.7/site-packages (0.2.5)
root@91WK-RT50:~# python
Python 2.7.17 (default, Nov 12 2019, 04:28:16) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import easysnmp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/easysnmp/__init__.py", line 1, in <module>
    from .easy import (  # noqa
  File "/usr/lib/python2.7/site-packages/easysnmp/easy.py", line 3, in <module>
    from .session import Session
  File "/usr/lib/python2.7/site-packages/easysnmp/session.py", line 8, in <module>
    from . import interface
ImportError: Error loading shared library /usr/lib/python2.7/site-packages/easysnmp/interface.so: Exec format error
>>>

**Comment by gmambro** [comment]
this is not that easysnmp but you may look into this one https://github.com/kamakazikamikaze/easysnmp/
